---
# See https://pre-commit.com for more information
default_language_version:
  python: python3

# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args:
          - '--maxkb=1024000'
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
        args:
          - '--fix=lf'
      - id: check-docstring-first
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
    - id: ruff-format
    - id: ruff-check
      args: ['--fix', '--exit-non-zero-on-fix']
